---
- name: install python-passlib
  apt: pkg=python-passlib state=installed

- name: awstats htpasswd for {{ item.key }}
  htpasswd: path={{awstats_output}}htpasswd_aw name={{ item.key | regex_replace('\.', '_')}}  password={{ item.value.awstats_password }} owner=root mode=0644 state=present create=yes
  with_dict: "{{ remap }}"
  when: not remap[item.key]["disable_logging"]

- name: awstats configuration file for {{ item.key }}
  template: src=awstats.generic.conf.j2 dest={{awstats_output}}awstats.{{item.key}}.conf owner=root group=root
  when: not remap[item.key]["disable_logging"]
  with_dict: "{{ remap }}"
